services:
  main:
    image: k8s_openvpn_docker_lab
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - $HOME/k8s_openvpn_lab/secret/ca.crt:/etc/openvpn/ca.crt
      - $HOME/k8s_openvpn_lab/secret/hub_1.crt:/etc/openvpn/client.crt
      - $HOME/k8s_openvpn_lab/secret/hub_1.key:/etc/openvpn/client.key
      - $HOME/k8s_openvpn_lab/conf/client.conf:/etc/openvpn/client.conf
      - $HOME/k8s_openvpn_lab/scripts/main.sh:/home/main.sh
    command: "/home/main.sh 34144444"
